//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionEntradaParking.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/parking")]
        public string rutaConexionBd {
            get {
                return ((string)(this["rutaConexionBd"]));
            }
            set {
                this["rutaConexionBd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NTY2OTI3QDMxMzkyZTM0MmUzMG85Q0toWFI2U2dGcVIwdjlXRHBDVGlHanpxZFlWVEJLcnZWUWtuSE5Ee" +
            "kU9")]
        public string licenciaSyncfusion {
            get {
                return ((string)(this["licenciaSyncfusion"]));
            }
            set {
                this["licenciaSyncfusion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://serviciocustomvision-prediction.cognitiveservices.azure.com/")]
        public string EndpointCustomVision {
            get {
                return ((string)(this["EndpointCustomVision"]));
            }
            set {
                this["EndpointCustomVision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54b8c577-9f3f-4ba6-8ca3-c93db2c812a8")]
        public string IdProyectoCustomVision {
            get {
                return ((string)(this["IdProyectoCustomVision"]));
            }
            set {
                this["IdProyectoCustomVision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Iteration1")]
        public string NombrePublicadoCustomVision {
            get {
                return ((string)(this["NombrePublicadoCustomVision"]));
            }
            set {
                this["NombrePublicadoCustomVision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dd24ccafdcf74d4481a473d6ae106b1e")]
        public string PredictionKeyCustomVision {
            get {
                return ((string)(this["PredictionKeyCustomVision"]));
            }
            set {
                this["PredictionKeyCustomVision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://serviciocomputervision.cognitiveservices.azure.com/")]
        public string EndpointComputerVision {
            get {
                return ((string)(this["EndpointComputerVision"]));
            }
            set {
                this["EndpointComputerVision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5414b463aa5740f28f7cbf74be73c5b2")]
        public string OcpApimSubscriptionKeyComputerVision {
            get {
                return ((string)(this["OcpApimSubscriptionKeyComputerVision"]));
            }
            set {
                this["OcpApimSubscriptionKeyComputerVision"] = value;
            }
        }
    }
}
